# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem  "daru"
gem 'nyaplot'
gem 'rumale'
gem 'pycall'
gem "ruby_linear_regression"